name: "CodeQL"

on:
  push:
    branches: [ main ]  # Specify which branches to trigger on push
  pull_request:
    branches: [ main ]  # Specify which branches to trigger on PR
  schedule:
    - cron: '0 1 * * 0'  # Scheduled run once a week at 01:00 on Sunday

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ['java', 'javascript', 'python']  # Specify languages

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
